openapi: 3.0.0
info:
  title: Assignment 3 - Licensing API
  description: API for managing licenses within organizations
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
    description: Local development server
paths:
  /organization/{organizationId}/license/{licenseId}:
    get:
      summary: Get license details
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
        - name: licenseId
          in: path
          required: true
          schema:
            type: string
        - name: Accept-Language
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
    delete:
      summary: Delete a license
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
        - name: licenseId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: License deleted
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /organization/{organizationId}/license:
    post:
      summary: Create a new license
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                licenseId:
                  type: string
                description:
                  type: string
                productName:
                  type: string
                licenseType:
                  type: string
      responses:
        '201':
          description: License created
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
    put:
      summary: Update an existing license
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                licenseId:
                  type: string
                description:
                  type: string
                productName:
                  type: string
                licenseType:
                  type: string
      responses:
        '200':
          description: License updated
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
